# GitHub action to build and deploy a NuGet package to Nuget.org

name: NuGet Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --configuration Release --no-build
        
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output artifacts ./src/ScryfallApi.Client/ScryfallApi.Client.csproj 